# Generated by Django 5.0.7 on 2024-08-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_publisher_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
