from practice_five.models import *
from django.utils import timezone
from datetime import timedelta
from random import randint, choice

# Функция для генерации случайной даты в диапазоне последних двух лет
def random_date_within_last_2_years():
    now = timezone.now()
    start_date = now - timedelta(days=2*365)  # Начало диапазона (2 года назад)
    random_days = randint(0, (now - start_date).days)  # Случайное количество дней в диапазоне
    random_date = start_date + timedelta(days=random_days)
    return random_date

def export_data():
    categories = [
        'Electronics', 'Books', 'Clothing', 'Home Appliances', 'Toys', 'Sports Equipment',
        'Groceries', 'Furniture', 'Health & Beauty', 'Automotive', 'Gardening',
        'Pet Supplies', 'Office Supplies', 'Jewelry', 'Footwear', 'Bags & Accessories',
        'Music Instruments', 'Art Supplies', 'Outdoor Gear', 'Baby Products',
        'Video Games', 'Movies & TV', 'Software', 'Hardware', 'Household Goods',
        'Kitchenware', 'Lighting', 'Stationery', 'Photography', 'Crafts'
    ]
    for category in categories:
        Category.objects.create(name=category)
    suppliers = [
        {'name': 'TechCorp', 'contact_email': 'info@techcorp.com', 'phone_number': '+1234567890'},
        {'name': 'BookWorld', 'contact_email': 'contact@bookworld.com', 'phone_number': '+1987654321'},
        {'name': 'FashionHub', 'contact_email': 'support@fashionhub.com', 'phone_number': '+1122334455'},
        {'name': 'HomeGoods', 'contact_email': 'service@homegoods.com', 'phone_number': '+1222333444'},
        {'name': 'ToyEmpire', 'contact_email': 'contact@toyempire.com', 'phone_number': '+1256789098'},
        {'name': 'Sporty', 'contact_email': 'info@sporty.com', 'phone_number': '+1987654329'},
        {'name': 'GroceryMart', 'contact_email': 'sales@grocerymart.com', 'phone_number': '+1345678901'},
        {'name': 'FurniWorld', 'contact_email': 'service@furniworld.com', 'phone_number': '+1445566778'},
        {'name': 'BeautyExpress', 'contact_email': 'info@beautyexpress.com', 'phone_number': '+1234567898'},
        {'name': 'AutoZone', 'contact_email': 'support@autozone.com', 'phone_number': '+1223344556'},
        {'name': 'GardenDepot', 'contact_email': 'contact@gardendepot.com', 'phone_number': '+1777888999'},
        {'name': 'PetParadise', 'contact_email': 'info@petparadise.com', 'phone_number': '+1333444555'},
        {'name': 'OfficeLand', 'contact_email': 'support@officeland.com', 'phone_number': '+1999888777'},
        {'name': 'JewelsRUs', 'contact_email': 'contact@jewelsrus.com', 'phone_number': '+1222999888'},
        {'name': 'ShoeHaven', 'contact_email': 'info@shoehaven.com', 'phone_number': '+1234123456'},
        {'name': 'BagBoutique', 'contact_email': 'sales@bagboutique.com', 'phone_number': '+1543210987'},
        {'name': 'MusicMania', 'contact_email': 'info@musicmania.com', 'phone_number': '+1234987654'},
        {'name': 'ArtStudio', 'contact_email': 'contact@artstudio.com', 'phone_number': '+1321321654'},
        {'name': 'OutdoorPro', 'contact_email': 'support@outdoorpro.com', 'phone_number': '+1333444111'},
        {'name': 'BabyBloom', 'contact_email': 'info@babybloom.com', 'phone_number': '+1999777666'},
        {'name': 'GameGalaxy', 'contact_email': 'sales@gamegalaxy.com', 'phone_number': '+1432198765'},
        {'name': 'CineWorld', 'contact_email': 'info@cineworld.com', 'phone_number': '+1555444333'},
        {'name': 'SoftShop', 'contact_email': 'support@softshop.com', 'phone_number': '+1444234234'},
        {'name': 'HardDepot', 'contact_email': 'contact@harddepot.com', 'phone_number': '+1777765432'},
        {'name': 'HouseNeeds', 'contact_email': 'info@houseneeds.com', 'phone_number': '+1234908765'},
        {'name': 'KitchenKing', 'contact_email': 'service@kitchenking.com', 'phone_number': '+1321321987'},
        {'name': 'BrightLights', 'contact_email': 'support@brightlights.com', 'phone_number': '+1777333555'},
        {'name': 'PaperPlus', 'contact_email': 'info@paperplus.com', 'phone_number': '+1234123789'},
        {'name': 'PhotoSpot', 'contact_email': 'sales@photospot.com', 'phone_number': '+1221987654'},
        {'name': 'CraftMaster', 'contact_email': 'info@craftmaster.com', 'phone_number': '+1444666777'}
    ]
    for supplier in suppliers:
        Supplier.objects.create(
            name=supplier['name'],
            contact_email=supplier['contact_email'],
            phone_number=supplier['phone_number']
        )
    categories = {
        'Electronics': Category.objects.get(name='Electronics'),
        'Books': Category.objects.get(name='Books'),
        'Clothing': Category.objects.get(name='Clothing'),
        'Home Appliances': Category.objects.get(name='Home Appliances'),
        'Toys': Category.objects.get(name='Toys'),
        'Sports Equipment': Category.objects.get(name='Sports Equipment'),
        'Groceries': Category.objects.get(name='Groceries'),
        'Furniture': Category.objects.get(name='Furniture'),
        'Health & Beauty': Category.objects.get(name='Health & Beauty'),
        'Automotive': Category.objects.get(name='Automotive'),
        'Gardening': Category.objects.get(name='Gardening'),
        'Pet Supplies': Category.objects.get(name='Pet Supplies'),
        'Office Supplies': Category.objects.get(name='Office Supplies'),
        'Jewelry': Category.objects.get(name='Jewelry'),
        'Footwear': Category.objects.get(name='Footwear'),
        'Bags & Accessories': Category.objects.get(name='Bags & Accessories'),
        'Music Instruments': Category.objects.get(name='Music Instruments'),
        'Art Supplies': Category.objects.get(name='Art Supplies'),
        'Outdoor Gear': Category.objects.get(name='Outdoor Gear'),
        'Baby Products': Category.objects.get(name='Baby Products'),
        'Video Games': Category.objects.get(name='Video Games'),
        'Movies & TV': Category.objects.get(name='Movies & TV'),
        'Software': Category.objects.get(name='Software'),
        'Hardware': Category.objects.get(name='Hardware'),
        'Household Goods': Category.objects.get(name='Household Goods'),
        'Kitchenware': Category.objects.get(name='Kitchenware'),
        'Lighting': Category.objects.get(name='Lighting'),
        'Stationery': Category.objects.get(name='Stationery'),
        'Photography': Category.objects.get(name='Photography'),
        'Crafts': Category.objects.get(name='Crafts')
    }
    suppliers = {
        'TechCorp': Supplier.objects.get(name='TechCorp'),
        'BookWorld': Supplier.objects.get(name='BookWorld'),
        'FashionHub': Supplier.objects.get(name='FashionHub'),
        'HomeGoods': Supplier.objects.get(name='HomeGoods'),
        'ToyEmpire': Supplier.objects.get(name='ToyEmpire'),
        'Sporty': Supplier.objects.get(name='Sporty'),
        'GroceryMart': Supplier.objects.get(name='GroceryMart'),
        'FurniWorld': Supplier.objects.get(name='FurniWorld'),
        'BeautyExpress': Supplier.objects.get(name='BeautyExpress'),
        'AutoZone': Supplier.objects.get(name='AutoZone'),
        'GardenDepot': Supplier.objects.get(name='GardenDepot'),
        'PetParadise': Supplier.objects.get(name='PetParadise'),
        'OfficeLand': Supplier.objects.get(name='OfficeLand'),
        'JewelsRUs': Supplier.objects.get(name='JewelsRUs'),
        'ShoeHaven': Supplier.objects.get(name='ShoeHaven'),
        'BagBoutique': Supplier.objects.get(name='BagBoutique'),
        'MusicMania': Supplier.objects.get(name='MusicMania'),
        'ArtStudio': Supplier.objects.get(name='ArtStudio'),
        'OutdoorPro': Supplier.objects.get(name='OutdoorPro'),
        'BabyBloom': Supplier.objects.get(name='BabyBloom'),
        'GameGalaxy': Supplier.objects.get(name='GameGalaxy'),
        'CineWorld': Supplier.objects.get(name='CineWorld'),
        'SoftShop': Supplier.objects.get(name='SoftShop'),
        'HardDepot': Supplier.objects.get(name='HardDepot'),
        'HouseNeeds': Supplier.objects.get(name='HouseNeeds'),
        'KitchenKing': Supplier.objects.get(name='KitchenKing'),
        'BrightLights': Supplier.objects.get(name='BrightLights'),
        'PaperPlus': Supplier.objects.get(name='PaperPlus'),
        'PhotoSpot': Supplier.objects.get(name='PhotoSpot'),
        'CraftMaster': Supplier.objects.get(name='CraftMaster')
    }
    products = [
        {'name': 'Smartphone', 'category': categories['Electronics'], 'supplier': suppliers['TechCorp'],
         'price': 499.99, 'quantity': 50, 'article': 'SP123', 'available': True},
        {'name': 'Laptop', 'category': categories['Electronics'], 'supplier': suppliers['TechCorp'], 'price': 899.99,
         'quantity': 30, 'article': 'LP456', 'available': True},
        {'name': 'Tablet', 'category': categories['Electronics'], 'supplier': suppliers['TechCorp'], 'price': 299.99,
         'quantity': 100, 'article': 'TB789', 'available': True},
        {'name': '4K TV', 'category': categories['Electronics'], 'supplier': suppliers['TechCorp'], 'price': 1200.00,
         'quantity': 25, 'article': 'TV101', 'available': True},
        {'name': 'Fiction Novel', 'category': categories['Books'], 'supplier': suppliers['BookWorld'], 'price': 15.99,
         'quantity': 150, 'article': 'BK123', 'available': True},
        {'name': 'Science Journal', 'category': categories['Books'], 'supplier': suppliers['BookWorld'], 'price': 9.99,
         'quantity': 200, 'article': 'BK456', 'available': True},
        {'name': 'History Textbook', 'category': categories['Books'], 'supplier': suppliers['BookWorld'],
         'price': 49.99, 'quantity': 75, 'article': 'BK789', 'available': True},
        {'name': 'Dress', 'category': categories['Clothing'], 'supplier': suppliers['FashionHub'], 'price': 79.99,
         'quantity': 50, 'article': 'CL123', 'available': True},
        {'name': 'T-shirt', 'category': categories['Clothing'], 'supplier': suppliers['FashionHub'], 'price': 19.99,
         'quantity': 200, 'article': 'CL456', 'available': True},
        {'name': 'Jeans', 'category': categories['Clothing'], 'supplier': suppliers['FashionHub'], 'price': 59.99,
         'quantity': 120, 'article': 'CL789', 'available': True},
        {'name': 'Refrigerator', 'category': categories['Home Appliances'], 'supplier': suppliers['HomeGoods'],
         'price': 899.99, 'quantity': 20, 'article': 'HA123', 'available': True},
        {'name': 'Washing Machine', 'category': categories['Home Appliances'], 'supplier': suppliers['HomeGoods'],
         'price': 599.99, 'quantity': 30, 'article': 'HA456', 'available': True},
        {'name': 'Microwave Oven', 'category': categories['Home Appliances'], 'supplier': suppliers['HomeGoods'],
         'price': 199.99, 'quantity': 40, 'article': 'HA789', 'available': True},
        {'name': 'Action Figure', 'category': categories['Toys'], 'supplier': suppliers['ToyEmpire'], 'price': 25.99,
         'quantity': 100, 'article': 'TY123', 'available': True},
        {'name': 'Puzzle Set', 'category': categories['Toys'], 'supplier': suppliers['ToyEmpire'], 'price': 14.99,
         'quantity': 150, 'article': 'TY456', 'available': True},
        {'name': 'Soccer Ball', 'category': categories['Sports Equipment'], 'supplier': suppliers['Sporty'],
         'price': 29.99, 'quantity': 100, 'article': 'SE123', 'available': True},
        {'name': 'Treadmill', 'category': categories['Sports Equipment'], 'supplier': suppliers['Sporty'],
         'price': 999.99, 'quantity': 10, 'article': 'SE456', 'available': True},
        {'name': 'Organic Apples', 'category': categories['Groceries'], 'supplier': suppliers['GroceryMart'],
         'price': 3.99, 'quantity': 500, 'article': 'GR123', 'available': True},
        {'name': 'Orange Juice', 'category': categories['Groceries'], 'supplier': suppliers['GroceryMart'],
         'price': 2.99, 'quantity': 300, 'article': 'GR456', 'available': True},
        {'name': 'Office Chair', 'category': categories['Furniture'], 'supplier': suppliers['FurniWorld'],
         'price': 199.99, 'quantity': 50, 'article': 'FU123', 'available': True},
        {'name': 'Dining Table', 'category': categories['Furniture'], 'supplier': suppliers['FurniWorld'],
         'price': 499.99, 'quantity': 20, 'article': 'FU456', 'available': True},
        {'name': 'Moisturizer Cream', 'category': categories['Health & Beauty'], 'supplier': suppliers['BeautyExpress'],
         'price': 19.99, 'quantity': 150, 'article': 'HB123', 'available': True},
        {'name': 'Shampoo', 'category': categories['Health & Beauty'], 'supplier': suppliers['BeautyExpress'],
         'price': 9.99, 'quantity': 200, 'article': 'HB456', 'available': True},
        {'name': 'Car Tire', 'category': categories['Automotive'], 'supplier': suppliers['AutoZone'], 'price': 79.99,
         'quantity': 100, 'article': 'AU123', 'available': True},
        {'name': 'Engine Oil', 'category': categories['Automotive'], 'supplier': suppliers['AutoZone'], 'price': 39.99,
         'quantity': 150, 'article': 'AU456', 'available': True},
        {'name': 'Garden Hose', 'category': categories['Gardening'], 'supplier': suppliers['GardenDepot'],
         'price': 25.99, 'quantity': 120, 'article': 'GD123', 'available': True},
        {'name': 'Lawn Mower', 'category': categories['Gardening'], 'supplier': suppliers['GardenDepot'],
         'price': 199.99, 'quantity': 30, 'article': 'GD456', 'available': True},
        {'name': 'Cat Food', 'category': categories['Pet Supplies'], 'supplier': suppliers['PetParadise'],
         'price': 19.99, 'quantity': 250, 'article': 'PS123', 'available': True},
        {'name': 'Dog Toy', 'category': categories['Pet Supplies'], 'supplier': suppliers['PetParadise'], 'price': 9.99,
         'quantity': 300, 'article': 'PS456', 'available': True},
        {'name': 'Printer Paper', 'category': categories['Office Supplies'], 'supplier': suppliers['OfficeLand'],
         'price': 14.99, 'quantity': 500, 'article': 'OS123', 'available': True},
        {'name': 'Stapler', 'category': categories['Office Supplies'], 'supplier': suppliers['OfficeLand'],
         'price': 9.99, 'quantity': 200, 'article': 'OS456', 'available': True},
        {'name': 'Gold Necklace', 'category': categories['Jewelry'], 'supplier': suppliers['JewelsRUs'],
         'price': 299.99, 'quantity': 40, 'article': 'JW123', 'available': True},
        {'name': 'Diamond Ring', 'category': categories['Jewelry'], 'supplier': suppliers['JewelsRUs'], 'price': 999.99,
         'quantity': 10, 'article': 'JW456', 'available': True},
        {'name': 'Running Shoes', 'category': categories['Footwear'], 'supplier': suppliers['ShoeHaven'],
         'price': 79.99, 'quantity': 120, 'article': 'FW123', 'available': True},
        {'name': 'Leather Boots', 'category': categories['Footwear'], 'supplier': suppliers['ShoeHaven'],
         'price': 149.99, 'quantity': 80, 'article': 'FW456', 'available': True},
        {'name': 'Leather Handbag', 'category': categories['Bags & Accessories'], 'supplier': suppliers['BagBoutique'],
         'price': 199.99, 'quantity': 50, 'article': 'BA123', 'available': True},
        {'name': 'Backpack', 'category': categories['Bags & Accessories'], 'supplier': suppliers['BagBoutique'],
         'price': 49.99, 'quantity': 150, 'article': 'BA456', 'available': True},
        {'name': 'Guitar', 'category': categories['Music Instruments'], 'supplier': suppliers['MusicMania'],
         'price': 299.99, 'quantity': 40, 'article': 'MI123', 'available': True},
        {'name': 'Drum Set', 'category': categories['Music Instruments'], 'supplier': suppliers['MusicMania'],
         'price': 799.99, 'quantity': 10, 'article': 'MI456', 'available': True},
        {'name': 'Acrylic Paint Set', 'category': categories['Art Supplies'], 'supplier': suppliers['ArtStudio'],
         'price': 19.99, 'quantity': 100, 'article': 'AS123', 'available': True},
        {'name': 'Canvas Board', 'category': categories['Art Supplies'], 'supplier': suppliers['ArtStudio'],
         'price': 9.99, 'quantity': 200, 'article': 'AS456', 'available': True},
        {'name': 'Camping Tent', 'category': categories['Outdoor Gear'], 'supplier': suppliers['OutdoorPro'],
         'price': 99.99, 'quantity': 30, 'article': 'OG123', 'available': True},
        {'name': 'Hiking Boots', 'category': categories['Outdoor Gear'], 'supplier': suppliers['OutdoorPro'],
         'price': 129.99, 'quantity': 50, 'article': 'OG456', 'available': True},
        {'name': 'Baby Stroller', 'category': categories['Baby Products'], 'supplier': suppliers['BabyBloom'],
         'price': 199.99, 'quantity': 30, 'article': 'BP123', 'available': True},
        {'name': 'Baby Monitor', 'category': categories['Baby Products'], 'supplier': suppliers['BabyBloom'],
         'price': 89.99, 'quantity': 50, 'article': 'BP456', 'available': True},
        {'name': 'Console Game', 'category': categories['Video Games'], 'supplier': suppliers['GameGalaxy'],
         'price': 59.99, 'quantity': 150, 'article': 'VG123', 'available': True},
        {'name': 'Gaming Headset', 'category': categories['Video Games'], 'supplier': suppliers['GameGalaxy'],
         'price': 79.99, 'quantity': 100, 'article': 'VG456', 'available': True},
        {'name': 'Blu-ray Movie', 'category': categories['Movies & TV'], 'supplier': suppliers['CineWorld'],
         'price': 19.99, 'quantity': 100, 'article': 'MT123', 'available': True},
        {'name': 'Streaming Subscription', 'category': categories['Movies & TV'], 'supplier': suppliers['CineWorld'],
         'price': 9.99, 'quantity': 500, 'article': 'MT456', 'available': True},
        {'name': 'Antivirus Software', 'category': categories['Software'], 'supplier': suppliers['SoftShop'],
         'price': 39.99, 'quantity': 200, 'article': 'SW123', 'available': True},
        {'name': 'Office Suite', 'category': categories['Software'], 'supplier': suppliers['SoftShop'], 'price': 99.99,
         'quantity': 100, 'article': 'SW456', 'available': True},
        {'name': 'SSD Drive', 'category': categories['Hardware'], 'supplier': suppliers['HardDepot'], 'price': 89.99,
         'quantity': 100, 'article': 'HD123', 'available': True},
        {'name': 'Graphics Card', 'category': categories['Hardware'], 'supplier': suppliers['HardDepot'],
         'price': 399.99, 'quantity': 50, 'article': 'HD456', 'available': True},
        {'name': 'Detergent', 'category': categories['Household Goods'], 'supplier': suppliers['HouseNeeds'],
         'price': 9.99, 'quantity': 300, 'article': 'HG123', 'available': True},
        {'name': 'Cleaning Spray', 'category': categories['Household Goods'], 'supplier': suppliers['HouseNeeds'],
         'price': 4.99, 'quantity': 400, 'article': 'HG456', 'available': True},
        {'name': 'Kitchen Knife Set', 'category': categories['Kitchenware'], 'supplier': suppliers['KitchenKing'],
         'price': 49.99, 'quantity': 100, 'article': 'KW123', 'available': True},
        {'name': 'Cookware Set', 'category': categories['Kitchenware'], 'supplier': suppliers['KitchenKing'],
         'price': 99.99, 'quantity': 50, 'article': 'KW456', 'available': True},
        {'name': 'LED Bulb', 'category': categories['Lighting'], 'supplier': suppliers['BrightLights'], 'price': 5.99,
         'quantity': 200, 'article': 'LT123', 'available': True},
        {'name': 'Table Lamp', 'category': categories['Lighting'], 'supplier': suppliers['BrightLights'],
         'price': 29.99, 'quantity': 70, 'article': 'LT456', 'available': True},
        {'name': 'Notebook', 'category': categories['Stationery'], 'supplier': suppliers['PaperPlus'], 'price': 3.99,
         'quantity': 300, 'article': 'ST123', 'available': True},
        {'name': 'Pen Set', 'category': categories['Stationery'], 'supplier': suppliers['PaperPlus'], 'price': 5.99,
         'quantity': 250, 'article': 'ST456', 'available': True},
        {'name': 'Digital Camera', 'category': categories['Photography'], 'supplier': suppliers['PhotoSpot'],
         'price': 499.99, 'quantity': 40, 'article': 'PH123', 'available': True},
        {'name': 'Tripod', 'category': categories['Photography'], 'supplier': suppliers['PhotoSpot'], 'price': 39.99,
         'quantity': 100, 'article': 'PH456', 'available': True},
        {'name': 'Craft Glue', 'category': categories['Crafts'], 'supplier': suppliers['CraftMaster'], 'price': 2.99,
         'quantity': 300, 'article': 'CR123', 'available': True},
        {'name': 'Knitting Yarn', 'category': categories['Crafts'], 'supplier': suppliers['CraftMaster'], 'price': 9.99,
         'quantity': 200, 'article': 'CR456', 'available': True}
    ]
    for product in products:
        Product.objects.create(
            name=product['name'],
            category=product['category'],
            supplier=product['supplier'],
            price=product['price'],
            quantity=product['quantity'],
            article=product['article'],
            available=product['available']
        )
    product_details_data = [
        {'product_name': 'Smartphone', 'description': 'High-end smartphone with latest features.',
         'manufacturing_date': '2023-01-01', 'expiration_date': None, 'weight': 0.15},
        {'product_name': 'Laptop', 'description': 'Lightweight and powerful laptop.',
         'manufacturing_date': '2023-03-15', 'expiration_date': None, 'weight': 2.5},
        {'product_name': 'Tablet', 'description': 'Portable tablet with high-resolution display.',
         'manufacturing_date': '2023-04-01', 'expiration_date': None, 'weight': 0.5},
        {'product_name': '4K TV', 'description': 'Ultra HD 4K TV with smart features.',
         'manufacturing_date': '2023-05-20', 'expiration_date': None, 'weight': 10.0},
        {'product_name': 'Fiction Novel', 'description': 'Engaging fiction novel from a renowned author.',
         'manufacturing_date': '2022-11-15', 'expiration_date': '2032-11-15', 'weight': 0.3},
        {'product_name': 'History Textbook', 'description': 'Comprehensive history textbook covering major events.',
         'manufacturing_date': '2022-08-10', 'expiration_date': '2032-08-10', 'weight': 1.2},
        {'product_name': 'Dress', 'description': 'Elegant evening dress.', 'manufacturing_date': '2023-01-10',
         'expiration_date': None, 'weight': 0.35},
        {'product_name': 'T-shirt', 'description': 'Comfortable cotton T-shirt.', 'manufacturing_date': '2023-02-20',
         'expiration_date': None, 'weight': 0.2},
        {'product_name': 'Jeans', 'description': 'Durable denim jeans.', 'manufacturing_date': '2023-02-05',
         'expiration_date': None, 'weight': 0.6},
        {'product_name': 'Refrigerator', 'description': 'Energy-efficient refrigerator.',
         'manufacturing_date': '2023-06-10', 'expiration_date': None, 'weight': 50.0},
        {'product_name': 'Washing Machine', 'description': 'Front-load washing machine with multiple modes.',
         'manufacturing_date': '2023-07-25', 'expiration_date': None, 'weight': 70.0},
        {'product_name': 'Microwave Oven', 'description': 'Compact microwave oven with advanced features.',
         'manufacturing_date': '2023-03-30', 'expiration_date': None, 'weight': 15.0},
        {'product_name': 'Action Figure', 'description': 'Detailed action figure from a popular series.',
         'manufacturing_date': '2023-05-01', 'expiration_date': None, 'weight': 0.25},
        {'product_name': 'Puzzle Set', 'description': '500-piece puzzle set for all ages.',
         'manufacturing_date': '2023-04-15', 'expiration_date': None, 'weight': 0.75},
        {'product_name': 'Soccer Ball', 'description': 'Standard size soccer ball.', 'manufacturing_date': '2023-01-10',
         'expiration_date': None, 'weight': 0.4},
        {'product_name': 'Treadmill', 'description': 'High-performance treadmill for home use.',
         'manufacturing_date': '2023-07-10', 'expiration_date': None, 'weight': 100.0},
        {'product_name': 'Organic Apples', 'description': 'Fresh organic apples from local farms.',
         'manufacturing_date': '2024-06-01', 'expiration_date': '2024-06-15', 'weight': 0.5},
        {'product_name': 'Orange Juice', 'description': '100% natural orange juice.',
         'manufacturing_date': '2024-06-01', 'expiration_date': '2024-06-10', 'weight': 1.0},
        {'product_name': 'Office Chair', 'description': 'Ergonomic office chair with lumbar support.',
         'manufacturing_date': '2023-03-15', 'expiration_date': None, 'weight': 15.0},
        {'product_name': 'Dining Table', 'description': 'Wooden dining table for 6 people.',
         'manufacturing_date': '2023-04-25', 'expiration_date': None, 'weight': 35.0},
        {'product_name': 'Moisturizer Cream', 'description': 'Hydrating moisturizer for daily use.',
         'manufacturing_date': '2023-02-20', 'expiration_date': '2025-02-20', 'weight': 0.2},
        {'product_name': 'Shampoo', 'description': 'Gentle shampoo suitable for all hair types.',
         'manufacturing_date': '2023-01-15', 'expiration_date': '2025-01-15', 'weight': 0.3},
        {'product_name': 'Car Tire', 'description': 'All-season car tire with excellent grip.',
         'manufacturing_date': '2023-03-20', 'expiration_date': None, 'weight': 10.0},
        {'product_name': 'Engine Oil', 'description': 'High-performance synthetic engine oil.',
         'manufacturing_date': '2023-05-01', 'expiration_date': '2025-05-01', 'weight': 1.5},
        {'product_name': 'Garden Hose', 'description': 'Flexible garden hose with adjustable nozzle.',
         'manufacturing_date': '2023-04-05', 'expiration_date': None, 'weight': 2.5},
        {'product_name': 'Lawn Mower', 'description': 'Electric lawn mower with adjustable height.',
         'manufacturing_date': '2023-06-10', 'expiration_date': None, 'weight': 25.0},
        {'product_name': 'Cat Food', 'description': 'Nutritious cat food with natural ingredients.',
         'manufacturing_date': '2023-03-25', 'expiration_date': '2024-03-25', 'weight': 2.0},
        {'product_name': 'Dog Toy', 'description': 'Durable toy for active dogs.', 'manufacturing_date': '2023-01-10',
         'expiration_date': None, 'weight': 0.15},
        {'product_name': 'Printer Paper', 'description': 'High-quality printer paper for all purposes.',
         'manufacturing_date': '2023-02-01', 'expiration_date': None, 'weight': 1.0},
        {'product_name': 'Stapler', 'description': 'Reliable stapler for office use.',
         'manufacturing_date': '2023-01-20', 'expiration_date': None, 'weight': 0.25},
        {'product_name': 'Gold Necklace', 'description': 'Elegant gold necklace with intricate design.',
         'manufacturing_date': '2023-02-15', 'expiration_date': None, 'weight': 0.02},
        {'product_name': 'Diamond Ring', 'description': 'Stunning diamond ring for special occasions.',
         'manufacturing_date': '2023-01-10', 'expiration_date': None, 'weight': 0.01},
        {'product_name': 'Running Shoes', 'description': 'Comfortable running shoes with cushioned sole.',
         'manufacturing_date': '2023-03-05', 'expiration_date': None, 'weight': 0.7},
        {'product_name': 'Leather Boots', 'description': 'Stylish leather boots for all seasons.',
         'manufacturing_date': '2023-02-10', 'expiration_date': None, 'weight': 1.2},
        {'product_name': 'Leather Handbag', 'description': 'Luxurious leather handbag with ample space.',
         'manufacturing_date': '2023-01-25', 'expiration_date': None, 'weight': 0.9},
        {'product_name': 'Backpack', 'description': 'Durable backpack for everyday use.',
         'manufacturing_date': '2023-02-15', 'expiration_date': None, 'weight': 0.5},
        {'product_name': 'Guitar', 'description': 'Acoustic guitar with rich sound.',
         'manufacturing_date': '2023-03-10', 'expiration_date': None, 'weight': 2.5},
        {'product_name': 'Drum Set', 'description': 'Complete drum set for beginners.',
         'manufacturing_date': '2023-05-20', 'expiration_date': None, 'weight': 15.0},
        {'product_name': 'Acrylic Paint Set', 'description': 'Set of vibrant acrylic paints.',
         'manufacturing_date': '2023-01-30', 'expiration_date': '2024-01-30', 'weight': 0.6},
        {'product_name': 'Canvas Board', 'description': 'High-quality canvas board for painting.',
         'manufacturing_date': '2023-02-15', 'expiration_date': None, 'weight': 1.0},
        {'product_name': 'Camping Tent', 'description': 'Spacious camping tent for 4 people.',
         'manufacturing_date': '2023-04-05', 'expiration_date': None, 'weight': 4.5},
        {'product_name': 'Hiking Boots', 'description': 'Waterproof hiking boots with excellent traction.',
         'manufacturing_date': '2023-03-20', 'expiration_date': None, 'weight': 1.5},
        {'product_name': 'Baby Stroller', 'description': 'Comfortable and safe baby stroller.',
         'manufacturing_date': '2023-05-10', 'expiration_date': None, 'weight': 10.0},
        {'product_name': 'Baby Monitor', 'description': 'High-definition baby monitor with night vision.',
         'manufacturing_date': '2023-03-15', 'expiration_date': None, 'weight': 0.3},
        {'product_name': 'Console Game', 'description': 'Exciting console game with high-quality graphics.',
         'manufacturing_date': '2023-01-10', 'expiration_date': None, 'weight': 0.1},
        {'product_name': 'Gaming Headset', 'description': 'Gaming headset with surround sound.',
         'manufacturing_date': '2023-02-20', 'expiration_date': None, 'weight': 0.5},
        {'product_name': 'Blu-ray Movie', 'description': 'High-definition Blu-ray movie.',
         'manufacturing_date': '2023-01-05', 'expiration_date': None, 'weight': 0.2},
        {'product_name': 'Streaming Subscription', 'description': 'One-year streaming subscription.',
         'manufacturing_date': '2023-01-01', 'expiration_date': '2024-01-01', 'weight': 0},
        {'product_name': 'Antivirus Software', 'description': 'Comprehensive antivirus protection for your PC.',
         'manufacturing_date': '2023-01-15', 'expiration_date': '2025-01-15', 'weight': 0},
        {'product_name': 'Office Suite', 'description': 'Office suite with word processing and spreadsheets.',
         'manufacturing_date': '2023-02-05', 'expiration_date': '2025-02-05', 'weight': 0},
        {'product_name': 'SSD Drive', 'description': 'High-speed SSD drive for faster performance.',
         'manufacturing_date': '2023-04-15', 'expiration_date': None, 'weight': 0.1},
        {'product_name': 'Graphics Card', 'description': 'Powerful graphics card for gaming and design.',
         'manufacturing_date': '2023-03-10', 'expiration_date': None, 'weight': 0.3},
        {'product_name': 'Detergent', 'description': 'Effective detergent for laundry.',
         'manufacturing_date': '2023-01-25', 'expiration_date': '2025-01-25', 'weight': 1.2},
        {'product_name': 'Cleaning Spray', 'description': 'Multi-surface cleaning spray.',
         'manufacturing_date': '2023-02-10', 'expiration_date': '2024-02-10', 'weight': 0.5},
        {'product_name': 'Kitchen Knife Set', 'description': 'Sharp kitchen knives in various sizes.',
         'manufacturing_date': '2023-03-05', 'expiration_date': None, 'weight': 1.5},
        {'product_name': 'Cookware Set', 'description': 'Durable cookware set for everyday cooking.',
         'manufacturing_date': '2023-04-20', 'expiration_date': None, 'weight': 8.0},
        {'product_name': 'LED Bulb', 'description': 'Energy-efficient LED bulb with long lifespan.',
         'manufacturing_date': '2023-01-30', 'expiration_date': None, 'weight': 0.1},
        {'product_name': 'Table Lamp', 'description': 'Stylish table lamp with adjustable brightness.',
         'manufacturing_date': '2023-02-25', 'expiration_date': None, 'weight': 2.0},
        {'product_name': 'Notebook', 'description': 'Lined notebook for writing and note-taking.',
         'manufacturing_date': '2023-01-15', 'expiration_date': None, 'weight': 0.3},
        {'product_name': 'Pen Set', 'description': 'Set of smooth-writing pens.', 'manufacturing_date': '2023-02-01',
         'expiration_date': None, 'weight': 0.05},
        {'product_name': 'Digital Camera', 'description': 'High-resolution digital camera with multiple features.',
         'manufacturing_date': '2023-05-10', 'expiration_date': None, 'weight': 0.6},
        {'product_name': 'Tripod', 'description': 'Stable tripod for cameras and camcorders.',
         'manufacturing_date': '2023-04-25', 'expiration_date': None, 'weight': 1.5},
        {'product_name': 'Craft Glue', 'description': 'Strong adhesive glue for crafts.',
         'manufacturing_date': '2023-01-05', 'expiration_date': '2025-01-05', 'weight': 0.1},
        {'product_name': 'Knitting Yarn', 'description': 'Soft yarn for knitting projects.',
         'manufacturing_date': '2023-02-10', 'expiration_date': None, 'weight': 0.3}
    ]
    for detail in product_details_data:
        product = Product.objects.get(name=detail['product_name'])
        ProductDetail.objects.create(
            product=product,
            description=detail['description'],
            manufacturing_date=detail['manufacturing_date'],
            expiration_date=detail['expiration_date'],
            weight=detail['weight']
        )
    addresses = [
        {'country': 'Germany', 'city': 'Berlin', 'street': 'Main St', 'house': '123'},
        {'country': 'Germany', 'city': 'Munich', 'street': 'High St', 'house': '45'},
        {'country': 'Germany', 'city': 'Hamburg', 'street': 'River Rd', 'house': '67'},
        {'country': 'Germany', 'city': 'Cologne', 'street': 'Forest St', 'house': '89'},
        {'country': 'Germany', 'city': 'Frankfurt', 'street': 'Market St', 'house': '101'},
        {'country': 'Germany', 'city': 'Stuttgart', 'street': 'Park Ave', 'house': '202'},
        {'country': 'Germany', 'city': 'Düsseldorf', 'street': 'Sunset Blvd', 'house': '303'},
        {'country': 'Germany', 'city': 'Dresden', 'street': 'Castle St', 'house': '404'},
        {'country': 'Germany', 'city': 'Leipzig', 'street': 'Old Town Rd', 'house': '505'},
        {'country': 'Germany', 'city': 'Bremen', 'street': 'Windmill Ln', 'house': '606'},
        {'country': 'Belarus', 'city': 'Minsk', 'street': 'Lenin St', 'house': '1'},
        {'country': 'Belarus', 'city': 'Gomel', 'street': 'Victory Ave', 'house': '22'},
        {'country': 'Belarus', 'city': 'Brest', 'street': 'Freedom Blvd', 'house': '33'},
        {'country': 'Belarus', 'city': 'Vitebsk', 'street': 'Unity St', 'house': '44'},
        {'country': 'Belarus', 'city': 'Grodno', 'street': 'Hero St', 'house': '55'},
        {'country': 'Belarus', 'city': 'Mogilev', 'street': 'Peace St', 'house': '66'},
        {'country': 'Belarus', 'city': 'Bobruisk', 'street': 'Red Square', 'house': '77'},
        {'country': 'Belarus', 'city': 'Baranovichi', 'street': 'Sunrise Blvd', 'house': '88'},
        {'country': 'Belarus', 'city': 'Pinsk', 'street': 'Central Ave', 'house': '99'},
        {'country': 'Belarus', 'city': 'Lida', 'street': 'Castle Rd', 'house': '101'},
        {'country': 'Ukraine', 'city': 'Kyiv', 'street': 'Independence Sq', 'house': '1001'},
        {'country': 'Ukraine', 'city': 'Lviv', 'street': 'Liberty Ave', 'house': '1002'},
        {'country': 'Ukraine', 'city': 'Odessa', 'street': 'Sea St', 'house': '1003'},
        {'country': 'Ukraine', 'city': 'Kharkiv', 'street': 'Freedom St', 'house': '1004'},
        {'country': 'Ukraine', 'city': 'Dnipro', 'street': 'River St', 'house': '1005'},
        {'country': 'Ukraine', 'city': 'Donetsk', 'street': 'Victory St', 'house': '1006'},
        {'country': 'Ukraine', 'city': 'Zaporizhia', 'street': 'Cosmos St', 'house': '1007'},
        {'country': 'Ukraine', 'city': 'Luhansk', 'street': 'Star St', 'house': '1008'},
        {'country': 'Ukraine', 'city': 'Kryvyi Rih', 'street': 'Metal St', 'house': '1009'},
        {'country': 'Ukraine', 'city': 'Mykolaiv', 'street': 'Shipyard St', 'house': '1010'},
        {'country': 'Ukraine', 'city': 'Simferopol', 'street': 'Crimea St', 'house': '2001'},
        {'country': 'Ukraine', 'city': 'Sevastopol', 'street': 'Fleet St', 'house': '2002'},
        {'country': 'Ukraine', 'city': 'Yalta', 'street': 'Resort Ave', 'house': '2003'},
        {'country': 'Ukraine', 'city': 'Feodosia', 'street': 'Marina Blvd', 'house': '2004'},
        {'country': 'Ukraine', 'city': 'Kerch', 'street': 'Bridge St', 'house': '2005'},
        {'country': 'Ukraine', 'city': 'Alushta', 'street': 'Mountain Rd', 'house': '2006'},
        {'country': 'Ukraine', 'city': 'Evpatoria', 'street': 'Spa St', 'house': '2007'},
        {'country': 'Ukraine', 'city': 'Sudak', 'street': 'Castle St', 'house': '2008'},
        {'country': 'Ukraine', 'city': 'Saki', 'street': 'Salt Lake Rd', 'house': '2009'},
        {'country': 'Ukraine', 'city': 'Bakhchisaray', 'street': 'Palace St', 'house': '2010'}
    ]
    # Создание записей для всех адресов
    for address in addresses:
        Address.objects.create(
            country=address['country'],
            city=address['city'],
            street=address['street'],
            house=address['house']
        )
    addresses = {
        'Berlin': Address.objects.get(street='Main St', house='123'),
        'Munich': Address.objects.get(street='High St', house='45'),
        'Hamburg': Address.objects.get(street='River Rd', house='67'),
        'Cologne': Address.objects.get(street='Forest St', house='89'),
        'Frankfurt': Address.objects.get(street='Market St', house='101'),
        'Stuttgart': Address.objects.get(street='Park Ave', house='202'),
        'Düsseldorf': Address.objects.get(street='Sunset Blvd', house='303'),
        'Dresden': Address.objects.get(street='Castle St', house='404'),
        'Leipzig': Address.objects.get(street='Old Town Rd', house='505'),
        'Bremen': Address.objects.get(street='Windmill Ln', house='606'),
        'Minsk': Address.objects.get(street='Lenin St', house='1'),
        'Gomel': Address.objects.get(street='Victory Ave', house='22'),
        'Brest': Address.objects.get(street='Freedom Blvd', house='33'),
        'Vitebsk': Address.objects.get(street='Unity St', house='44'),
        'Grodno': Address.objects.get(street='Hero St', house='55'),
        'Mogilev': Address.objects.get(street='Peace St', house='66'),
        'Bobruisk': Address.objects.get(street='Red Square', house='77'),
        'Baranovichi': Address.objects.get(street='Sunrise Blvd', house='88'),
        'Pinsk': Address.objects.get(street='Central Ave', house='99'),
        'Lida': Address.objects.get(street='Castle Rd', house='101'),
        'Kyiv': Address.objects.get(street='Independence Sq', house='1001'),
        'Lviv': Address.objects.get(street='Liberty Ave', house='1002'),
        'Odessa': Address.objects.get(street='Sea St', house='1003'),
        'Kharkiv': Address.objects.get(street='Freedom St', house='1004'),
        'Dnipro': Address.objects.get(street='River St', house='1005'),
        'Donetsk': Address.objects.get(street='Victory St', house='1006'),
        'Zaporizhia': Address.objects.get(street='Cosmos St', house='1007'),
        'Luhansk': Address.objects.get(street='Star St', house='1008'),
        'Kryvyi Rih': Address.objects.get(street='Metal St', house='1009'),
        'Mykolaiv': Address.objects.get(street='Shipyard St', house='1010'),
        'Simferopol': Address.objects.get(street='Crimea St', house='2001'),
        'Sevastopol': Address.objects.get(street='Fleet St', house='2002'),
        'Yalta': Address.objects.get(street='Resort Ave', house='2003'),
        'Feodosia': Address.objects.get(street='Marina Blvd', house='2004'),
        'Kerch': Address.objects.get(street='Bridge St', house='2005'),
        'Alushta': Address.objects.get(street='Mountain Rd', house='2006'),
        'Evpatoria': Address.objects.get(street='Spa St', house='2007'),
        'Sudak': Address.objects.get(street='Castle St', house='2008'),
        'Saki': Address.objects.get(street='Salt Lake Rd', house='2009'),
        'Bakhchisaray': Address.objects.get(street='Palace St', house='2010')
    }
    customers = [
        {'first_name': 'John', 'last_name': 'Doe', 'email': 'john.doe@example.com', 'phone_number': '+491234567890',
         'address': addresses['Berlin']},
        {'first_name': 'Jane', 'last_name': 'Smith', 'email': 'jane.smith@example.com', 'phone_number': '+4910987654321',
         'address': addresses['Munich']},
        {'first_name': 'Alice', 'last_name': 'Johnson', 'email': 'alice.johnson@example.com',
         'phone_number': '+491111222333', 'address': addresses['Hamburg']},
        {'first_name': 'Bob', 'last_name': 'Brown', 'email': 'bob.brown@example.com', 'phone_number': '+492233445566',
         'address': addresses['Cologne']},
        {'first_name': 'Charlie', 'last_name': 'Davis', 'email': 'charlie.davis@example.com',
         'phone_number': '+493344556677', 'address': addresses['Frankfurt']},
        {'first_name': 'David', 'last_name': 'Clark', 'email': 'david.clark@example.com', 'phone_number': '+494455667788',
         'address': addresses['Stuttgart']},
        {'first_name': 'Eve', 'last_name': 'Martinez', 'email': 'eve.martinez@example.com', 'phone_number': '+495566778899',
         'address': addresses['Düsseldorf']},
        {'first_name': 'Frank', 'last_name': 'Harris', 'email': 'frank.harris@example.com', 'phone_number': '+496677889900',
         'address': addresses['Dresden']},
        {'first_name': 'Grace', 'last_name': 'Clark', 'email': 'grace.clark@example.com', 'phone_number': '+497788990011',
         'address': addresses['Leipzig']},
        {'first_name': 'Hank', 'last_name': 'White', 'email': 'hank.white@example.com', 'phone_number': '+498899001122',
         'address': addresses['Bremen']},
        {'first_name': 'Ivy', 'last_name': 'Moore', 'email': 'ivy.moore@example.com', 'phone_number': '+375291234567',
         'address': addresses['Minsk']},
        {'first_name': 'Jack', 'last_name': 'Taylor', 'email': 'jack.taylor@example.com', 'phone_number': '+375291098765',
         'address': addresses['Gomel']},
        {'first_name': 'Karen', 'last_name': 'Anderson', 'email': 'karen.anderson@example.com',
         'phone_number': '+375297654321', 'address': addresses['Brest']},
        {'first_name': 'Liam', 'last_name': 'Thomas', 'email': 'liam.thomas@example.com', 'phone_number': '+375291112223',
         'address': addresses['Vitebsk']},
        {'first_name': 'Mia', 'last_name': 'Jackson', 'email': 'mia.jackson@example.com', 'phone_number': '+375291223344',
         'address': addresses['Grodno']},
        {'first_name': 'Noah', 'last_name': 'Lee', 'email': 'noah.lee@example.com', 'phone_number': '+375291334455',
         'address': addresses['Mogilev']},
        {'first_name': 'Olivia', 'last_name': 'Perez', 'email': 'olivia.perez@example.com', 'phone_number': '+375291445566',
         'address': addresses['Bobruisk']},
        {'first_name': 'Paul', 'last_name': 'Walker', 'email': 'paul.walker@example.com', 'phone_number': '+375291556677',
         'address': addresses['Baranovichi']},
        {'first_name': 'Quinn', 'last_name': 'Robinson', 'email': 'quinn.robinson@example.com',
         'phone_number': '+375291667788', 'address': addresses['Pinsk']},
        {'first_name': 'Ruby', 'last_name': 'Lopez', 'email': 'ruby.lopez@example.com', 'phone_number': '+375291778899',
         'address': addresses['Lida']},
        {'first_name': 'Sam', 'last_name': 'Gonzalez', 'email': 'sam.gonzalez@example.com', 'phone_number': '+380631234567',
         'address': addresses['Kyiv']},
        {'first_name': 'Tina', 'last_name': 'Young', 'email': 'tina.young@example.com', 'phone_number': '+380631098765',
         'address': addresses['Lviv']},
        {'first_name': 'Uma', 'last_name': 'Hall', 'email': 'uma.hall@example.com', 'phone_number': '+380637654321',
         'address': addresses['Odessa']},
        {'first_name': 'Victor', 'last_name': 'Allen', 'email': 'victor.allen@example.com', 'phone_number': '+380631112223',
         'address': addresses['Kharkiv']},
        {'first_name': 'Wendy', 'last_name': 'King', 'email': 'wendy.king@example.com', 'phone_number': '+380631223344',
         'address': addresses['Dnipro']},
        {'first_name': 'Xavier', 'last_name': 'Scott', 'email': 'xavier.scott@example.com', 'phone_number': '+380631334455',
         'address': addresses['Donetsk']},
        {'first_name': 'Yara', 'last_name': 'Torres', 'email': 'yara.torres@example.com', 'phone_number': '+380631445566',
         'address': addresses['Zaporizhia']},
        {'first_name': 'Zane', 'last_name': 'Green', 'email': 'zane.green@example.com', 'phone_number': '+380631556677',
         'address': addresses['Luhansk']},
        {'first_name': 'Adam', 'last_name': 'Baker', 'email': 'adam.baker@example.com', 'phone_number': '+380631667788',
         'address': addresses['Kryvyi Rih']},
        {'first_name': 'Bella', 'last_name': 'Nelson', 'email': 'bella.nelson@example.com', 'phone_number': '+380631778899',
         'address': addresses['Mykolaiv']},
        {'first_name': 'Chris', 'last_name': 'Carter', 'email': 'chris.carter@example.com', 'phone_number': '+380632223344',
         'address': addresses['Simferopol']},
        {'first_name': 'Dana', 'last_name': 'Mitchell', 'email': 'dana.mitchell@example.com',
         'phone_number': '+380632334455', 'address': addresses['Sevastopol']},
        {'first_name': 'Ethan', 'last_name': 'Perez', 'email': 'ethan.perez@example.com', 'phone_number': '+380632445566',
         'address': addresses['Yalta']},
        {'first_name': 'Fiona', 'last_name': 'Roberts', 'email': 'fiona.roberts@example.com',
         'phone_number': '+380632556677', 'address': addresses['Feodosia']},
        {'first_name': 'George', 'last_name': 'Phillips', 'email': 'george.phillips@example.com',
         'phone_number': '+380632667788', 'address': addresses['Kerch']},
        {'first_name': 'Hannah', 'last_name': 'Campbell', 'email': 'hannah.campbell@example.com',
         'phone_number': '+380632778899', 'address': addresses['Alushta']},
        {'first_name': 'Ian', 'last_name': 'Evans', 'email': 'ian.evans@example.com', 'phone_number': '+380632889900',
         'address': addresses['Evpatoria']},
        {'first_name': 'Jenna', 'last_name': 'Reed', 'email': 'jenna.reed@example.com', 'phone_number': '+380632990011',
         'address': addresses['Sudak']},
        {'first_name': 'Kyle', 'last_name': 'Gray', 'email': 'kyle.gray@example.com', 'phone_number': '+380633001122',
         'address': addresses['Saki']},
        {'first_name': 'Lana', 'last_name': 'Morris', 'email': 'lana.morris@example.com', 'phone_number': '+380633112233',
         'address': addresses['Bakhchisaray']}
    ]
    for customer in customers:
        Customer.objects.create(
            first_name=customer['first_name'],
            last_name=customer['last_name'],
            email=customer['email'],
            phone_number=customer['phone_number'],
            address=customer['address'],
            date_joined=timezone.now()
        )
    # Получите всех клиентов
    customers = list(Customer.objects.all())
    # Создайте 1,000 заказов
    for _ in range(1000):
        # Выберите случайного клиента
        customer = choice(customers)
        # Создайте заказ с случайной датой
        Order.objects.create(
            customer=customer,
            order_date=random_date_within_last_2_years()
        )
    # Получите все заказы и продукты
    orders = Order.objects.all()
    products = list(Product.objects.all())
    # Создайте позиции заказа для каждого заказа
    for order in orders:
        # Случайно выберите количество позиций в заказе от 1 до 5
        num_items = randint(1, 5)
        for _ in range(num_items):
            # Случайно выберите продукт
            product = choice(products)
            # Случайное количество от 1 до доступного количества на складе или 5, если продукта достаточно
            quantity = randint(1, min(product.quantity, 5))
            # Цена за единицу продукта
            price = product.price
            # Создайте позицию заказа
            OrderItem.objects.create(
                order=order,
                product=product,
                quantity=quantity,
                price=price
            )