# Generated by Django 5.0.7 on 2024-08-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicum_two', '0002_projectfile_alter_project_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='practicum_two.projectfile'),
        ),
    ]
