# Generated by Django 5.0.7 on 2024-08-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_five', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': 'order_date', 'ordering': ['-order_date'], 'permissions': [('can_view_statistics', 'Can view statistics')]},
        ),
    ]
