# Generated by Django 5.0.7 on 2024-08-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
    ]
